mozilla/universal-search-recommendation

.env.dist
README.md
app/conf.py
app/main.py
app/memcached.py
app/memorize.py
app/requirements.txt
app/search/classification/__init__.py
app/search/classification/base.py
app/search/classification/domain.py
app/search/classification/wikipedia.py
app/search/query/base.py
app/search/query/yahoo.py
app/search/recommendation.py
app/search/suggest/base.py
app/search/suggest/bing.py
setup.py

Example response from a request to `http://localhost:5000/?q=wiki%20the%20marti`
```json
{
"enhancements": {
"wikipedia": {
"abstract": "The Martian is a 2011 science fiction novel. It was the second novel by American author Andy Weir and the first published under his own name. It was originally self-published in 2011 after which Crown Publishing purchased the rights and re-released it in 2014. The story follows an American astronaut, Mark Watney, as he becomes stranded alone on Mars in the year 2035 and must improvise in order to survive. The Martian, a film adaptation directed by Ridley Scott and starring Matt Damon, was released in October 2015.",
"slug": "The_Martian_(Andy_Weir)",
"title": "The Martian (Weir novel)"
}
},
"query": {
"completed": "wiki the martian",
"original": "wiki …
```

Approximate clone of Tiny Machine.

---

README.md
requirements.txt

Badge for `mozilla/master`:
[![Requirements Status](https://requires.io/github/mozilla/universal-search-recommendation/requirements.svg?branch=master)](https://requires.io/github/mozilla/universal-search-recommendation/requirements/?branch=master)

Add requires.io badge to README; update outdated requirements (closes #14).

---

.gitignore
README.md
app/memcached.py
app/search/recommendation.py
app/search/tests/test_recommendation.py
application.py
docs/deploy.md
requirements.txt
setup.py

Prepare for deployment to development environment (closes #17).

---

conf/nginx/Dockerfile
conf/nginx/contribute.json
conf/nginx/recommendation.conf

Validation: https://www.contributejson.org/https:%252F%252Fraw.githubusercontent.com%252Fchuckharmston%252Funiversal-search-recommendation%252F094a9b9a99cb9830fdb3d0212f7b96c0df3104f8%252Fconf%252Fnginx%252Fcontribute.json
Served by nginx:
r? @6a68 
Also optional r? for the content of the file contribute.json: @pmclanahan

Adds contribute.json, serves at /contribute.json (closes #22).

---

docs/api.md

Preview: https://github.com/chuckharmston/universal-search-recommendation/blob/6-api-docs/docs/api.md

Adds API consumer docs (closes #6).

---

app/cors.py
app/main.py
app/tests/test_main.py

*To-do:*
Creating PR to let CI do its thing.

Adds CORS headers to recommendation endpoint (closes #36).

---

app/requirements.txt

PR to make sure that the full CI rigamarole passes before merging.

Updates point versions of several dependencies.

---

README.md
app/Dockerfile
app/requirements.txt
circle.yml
setup.cfg

r? @mostlygeek @6a68 
I'll work towards #43 once this gets merged.

Adds CircleCI configuration (closes #40).

---

app/conf.py
app/entry.sh

Uses $PORT on host (closes #45).

---

Dockerfile
recommendation/memcached.py
requirements.txt

Uses pylibmc instead of python-memcached (closes #42).

---

recommendation/factory.py
recommendation/views/data/dummy.py
recommendation/views/dummy.py
recommendation/views/tests/test_dummy.py

If tests pass, I'm going to YOLO-merge it.

Adds dummy data view (closes #58).

---

requirements.txt

Changes: https://github.com/celery/celery/compare/v3.1.20...v3.1.21

Updates point version of Celery.

---

requirements.txt

https://github.com/celery/celery/compare/v3.1.21...v3.1.22

Bump point version of Celery.

---

recommendation/views/data/dummy.py
recommendation/views/dummy.py
recommendation/views/tests/test_dummy.py

Turns out we'll probably use the size information to work around some XUL limitations.
r? @6a68

Adds dummy domain classifier; adds dummy embedly image sizes.

---

recommendation/search/classification/embedly.py
recommendation/search/classification/tests/test_embedly.py
recommendation/search/tests/test_recommendation.py

Academic at this point, but worth committing in case we regain access.
r? @6a68

Include all the favicons (closes #56).

---

recommendation/conf.py
recommendation/search/query/bing.py
recommendation/search/query/tests/test_bing.py
recommendation/search/recommendation.py

Adds Bing query engine (closes #65).

---

requirements.txt

Changelog: https://github.com/lericson/pylibmc/compare/1.5.0...1.5.1

Updates point version of pylibmc

---

recommendation/search/classification/__init__.py
recommendation/search/classification/embedly.py
recommendation/search/classification/tests/test_embedly.py
recommendation/search/tests/test_recommendation.py

Adds favicon classifier, removes favicon info from Embedly classifier (closes #67).

---

README.md

* Uses shields.io for badges (more consistent visually).
* Adds "Contributing" section from the addon repository.

Updates README:

---

recommendation/search/recommendation.py

Just realized that I never pushed a change to use Yahoo again.
r? @6a68

Uses Yahoo as default query engine.

---

recommendation/search/classification/__init__.py
recommendation/search/classification/embedly.py
recommendation/search/classification/tests/test_embedly.py
recommendation/search/tests/test_recommendation.py

r? @6a68 
```json
$ http get http://universal-search.dev/\?q\=the%20mart
{
"enhancements": {
"favicon": {
"color": [
181,
150,
34
],
"url": "https://i.embed.ly/1/image?url=http%3A%2F%2Fia.media-imdb.com%2Fimages%2FG%2F01%2Fimdb%2Fimages%2Fdesktop-favicon-2165806970._CB379390718_.ico&key=11ecbb09b10d4f8cb59beb77741c7105"
},
"keyimage": {
"height": 1200,
"url": "https://i.embed.ly/1/image?url=http%3A%2F%2Fia.media-imdb.com%2Fimages%2FM%2FMV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE%40._V1_UY1200_CR90%2C0%2C630%2C1200_AL_.jpg&key=11ecbb09b10d4f8cb59beb77741c7105",
"width": 630
}
},
"query": {
"completed": "the martian",
"original": "the mart"
},
"result": {
"abstract": "Directed by Ridley Scott. With Matt Damon, Jessica Chastain, Kristen Wiig, Kate Mara. During a manned mission to Mars, …
```

Adds KeyImageClassifier to all responses (closes #78).

---

recommendation/search/suggest/bing.py
recommendation/search/suggest/tests/test_bing.py

Handles gracefully instances where Bing returns full web search results (closes #80).

---

recommendation/conf.py
recommendation/memorize.py
recommendation/tasks/task_recommend.py
recommendation/views/main.py
recommendation/views/tests/test_main.py

* Cache-Control headers on 200 responses.
* Memcached TTLs.
* Environment variables to configure each.
Closes #85.

Adds cache TTLs:

---

requirements.txt

https://github.com/pallets/werkzeug/compare/0.11.5...0.11.7

Updates Werkzeug to 0.11.7.

---

requirements.txt

A few bug and test fixes, nothing major: https://github.com/GrahamDumpleton/wrapt/compare/1.10.6...1.10.8

Updates to wrapt 1.10.8.

---

recommendation/search/query/bing.py
recommendation/search/query/tests/test_bing.py
recommendation/search/query/tests/test_yahoo.py
recommendation/search/query/yahoo.py

Excludes adult content from Yahoo and Bing query engines (closes #90).

---

recommendation/tasks/task_recommend.py
recommendation/tasks/tests/test_recommend.py

f66d4b3 is the commit here; I needed to base this branch on the fix for #28, which must be merged before this.
r? @6a68

Makes searches case-insensitive (closes #101).

---

README.md

Obviously we'll hold off on merging until we're live; just getting the PR up now. Also need to rebase against master after #75 lands.
Preview it here: https://github.com/mozilla/universal-search-recommendation/blob/testpilot-badge/README.md

Adds 'available on | Test Pilot' badge to README.

---

requirements.txt

Changelog: https://github.com/pallets/werkzeug/blob/479e6534f551134f1481988b0e5fcb938a39a979/CHANGES#L4-L22
Will merge if tests pass.

Bumps Werkzeug to 0.11.9.

---

recommendation/mozlog/middleware.py
recommendation/mozlog/tests/test_middleware.py

Removed nested objects in request summary logs (closes #116).

---

requirements.txt

https://github.com/kennethreitz/requests/compare/v2.9.1...v2.10.0

Updates requests to 2.10.0.

---

recommendation/mozlog/middleware.py
recommendation/mozlog/tests/test_middleware.py

Forces lowercase before logging queries (closes #136).
